### ISSUE TITLE
The test //rust/tools/authorization-logic:authorization_logic_test may be nondeterministic.

### ISSUE THREAD

**Issue by markww** [google-research/raksha#464]
Recently, I was running my tests to ensure everything was working as expected and was surprised to see that the test `//rust/tools/authorization-logic:authorization_logic_test` failed. In hopes of getting the failure message on a cleaner terminal output, I reran `bazel test ...`. After that, the test passed. Unfortunately, this also appears to have deleted the failing logs.

Because of the above behavior, it seems likely that `//rust/tools/authorization-logic:authorization_logic_test` is nondeterministic in some way, perhaps due to a dependency that Bazel does not have insight into. In any case, we should look into this if it pops up again.

**Comment by Cypher1** [comment]
I ran
```
bazel test //rust/tools/authorization-logic:authorization_logic_test --runs_per_test=100
```
and got
```
FAILED in 55 out of 100 in 1.0s
```

So this is definitely flakey. Can look into it further but not sure where to start.

It looks like the failures are related to the file system but here's the numbers from
```
cat  /home/jopra/.cache/bazel/_bazel_jopra/ad57f266c437944f14d502fbbd0016f5/execroot/__main__/bazel-out/k8-fastbuild/testlogs/rust/tools/authorization-logic/authorization_logic_test/run_*_of_100/test.log | grep "panicked at" | sort | uniq -c
```
Sorted and counted:
```
5 thread 'test::test_dots_and_quotes::test::test_quotes_in_paths' panicked at 'failed to read input in input_to_souffle_file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', rust/tools/authorization-logic/src/compilation_top_level.rs:38:10
      1 thread 'test::test_multimic_no_overrides::test::test_multimic_no_overrides_scenario2' panicked at 'assertion failed: is_file_empty(&queryfile) != intended_result', rust/tools/authorization-logic/src/test/test_queries.rs:64:13
      2 thread 'test::test_multimic_overrides::test::test_multimic_overrides' panicked at 'assertion failed: is_file_empty(&queryfile) != intended_result', rust/tools/authorization-logic/src/test/test_queries.rs:64:13
     32 thread 'test::test_num_compare::test::test_basic_number_comparisons' panicked at 'failed to read input in input_to_souffle_file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', rust/tools/authorization-logic/src/souffle/souffle_interface.rs:45:10
     42 thread 'test::test_num_compare::test::test_comparisons_with_delegation' panicked at 'failed to read input in input_to_souffle_file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', rust/tools/authorization-logic/src/souffle/souffle_interface.rs:45:10
     15 thread 'test::test_relation_declarations::test::test_relation_declarations' panicked at 'failed to read input in input_to_souffle_file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', rust/tools/authorization-logic/src/compilation_top_level.rs:38:10
```

I think this points to there being a race between the code that creates the files for souffle to read and souffle's execution, and possibly other races reading souffle's output, possibly more.

Hope this makes narrowing the issue down easier

**Comment by Cypher1** [comment]
I took a first step in making this easier to debug here:
https://github.com/google-research/raksha/pull/466
But I'm not sure if this fits with Raksha style or is the right direction to go in.

**Comment by aferr** [comment]
Thanks for looking into this @Cypher1!

FWIW occasionally `$AUTH_LOGIC/src/test/test_negation.rs` will randomly fail when just run using `cargo test`.

I thought it maybe had something to do with the fact that cargo runs tests in parallel and maybe the code for setting up tests doesn't quite do the right thing with setting up directories under the assumption that it's happening more than once in parallel.

**Comment by aferr** [comment]
It could have to do with `clean_test_dir()` in `.../src/test/test_queries.rs`

**Comment by aferr** [comment]
Ohhhh... another relevant thing might be that many of these tests produce CSVs to output the results of queries. All these CSVs are produced into the same directory, and I wasn't naming the queries to avoid name collisions. (I haven't actually looked to confirm this though).

**Comment by aferr** [comment]
In case the way queries are produced is the cause, an issue tracks fixing that now (https://github.com/google-research/raksha/issues/468)

**Comment by shaper** [comment]
I am seeing this flakiness now myself at clean ToT, via:
```
% bazel test --cache_test_results=no --test_output=all --runs_per_test=100 //rust/tools/authorization-logic:authorization_logic_test
```

Results:

```
//rust/tools/authorization-logic:authorization_logic_test                FAILED in 67 out of 100 in 1.8s
```
More detail for just one from test error output in case there's new file info given @Cypher1 change above:

```
failures:

---- test::test_num_compare::test::test_comparisons_with_delegation stdout ----
thread 'test::test_num_compare::test::test_comparisons_with_delegation' panicked at 'failed to read input in input_to_souffle_file: /usr/local/google/home/wkorman/.cache/bazel/_bazel_wkorman/c285be7244670f928b674468ca742163/sandbox/linux-sandbox/2711/execroot/__main__/_tmp/ab6bb43daa4b40ad4dcd1335cfc70a08/test_inputs/comparisons_with_delegation
No such file or directory (os error 2)', rust/tools/authorization-logic/src/souffle/souffle_interface.rs:44:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test::test_num_compare::test::test_comparisons_with_delegation

test result: FAILED. 19 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.38s
```

**Comment by shaper** [comment]
> It could have to do with `clean_test_dir()` in `.../src/test/test_queries.rs`

This function is dead code at ToT, I have a PR that restores it presuming it was intended to be called at the end of `setup_dirs_and_run_query_test`, but doing so doesn't seem to de-flake things FWIW.
